src/App.test.js
webpack.config.js

```javascript
...
entry: "./src/index.jsx",
output: {
filename: "bundle.js",
path: path.resolve(__dirname, "build"),  // <--- /build 에서 build로 변경
publicPath: "/",
},
...
```

[hotfix] 웹팩 빌드 설정 변경

---

src/router/router.jsx

hotfix: router import 경로 수정

---

package.json
src/components/Button.test.tsx
src/components/Button.tsx
yarn.lock

#18 
활성화/비활성화 상태에 따른 클릭 가능/불가능 여부 테스트

[Test] car button test

---

src/assets/svg/RefreshButton.tsx
src/pages/mainPage/ColorSection.tsx
src/pages/mainPage/ConvenienceDescriptionItem.tsx
src/pages/mainPage/ConvenienceSection.tsx
src/pages/mainPage/DriveDescriptionItem.tsx
src/pages/mainPage/DriveSection.tsx
src/pages/mainPage/EventFooter.tsx
src/pages/mainPage/EventHeader.tsx
src/pages/mainPage/EventSelectOptions.tsx
src/pages/mainPage/EventSelectSection.tsx
src/pages/mainPage/FCFSEventSection.tsx
src/pages/mainPage/GuideItem.tsx
src/pages/mainPage/InfoScreen.tsx
src/pages/mainPage/InsideSection.tsx
src/pages/mainPage/LandingScreen.tsx
src/pages/mainPage/MainPage.tsx
src/pages/mainPage/MainScreen.tsx
src/pages/mainPage/NavElement.tsx
src/pages/mainPage/NavigationBar.tsx
src/pages/mainPage/NotificationScreen.tsx
src/pages/mainPage/OutsideDescriptionItem.tsx
src/pages/mainPage/OutsideSection.tsx
src/pages/mainPage/PerformanceDescriptionItem.tsx
src/pages/mainPage/PerformanceSection.tsx
src/pages/mainPage/RandomEventSection.tsx
src/pages/mainPage/Timer.tsx

#15 
기존에 작성한 컴포넌트 설계도를 따라 컴포넌트 뼈대 작성

[Feat] mainPage에 대해 컴포넌트 설계도를 따라 컴포넌트 뼈대 작성

---

src/components/randomEventPage/Option/Option.stories.tsx
src/components/randomEventPage/Option/Option.test.tsx
src/components/randomEventPage/Option/Option.tsx
src/constants/RandomEventData.ts
src/pages/randomEventPage/RandomQuizSection.stories.tsx
src/pages/randomEventPage/RandomQuizSection.test.tsx
src/pages/randomEventPage/RandomQuizSection.tsx

#28 
https://github.com/user-attachments/assets/c279e9b3-5a1a-4d7e-82d4-6d25d5b6f9cf
Option 컴포넌트
```
/**
* 운전자 유형 테스트 선택지
* @param label 선택지 A,B
* @param content 내용
* @param state default, selected, unselected
* @param onClick onClick 함수
* @returns
*/
```

[Feature] event2 quiz section 개발

---

package.json
webpack.common.js
webpack.dev.js
webpack.prod.js

[webpack production](https://webpack.kr/guides/production/)

[Chore] webpack 개발과 배포 버전 설정 파일 분리

---

webpack.common.js

test: git test

---

src/App.tsx
src/pages/providers     /AppProvider.tsx

#18 
useAppContext hook 을 이용해서
{isAuth, setIsAuth, isFCFSEnd, setIsFCFSEnd, isRandomEnd, setIsRandomEnd}
값 사용 가능

[Feature] 전역으로 정의된 context 생성

---

src/App.tsx
src/components/common/AuthTooltip/AuthTooltip.test.tsx
src/components/common/Toast/Toast.test.tsx
src/components/common/Toast/Toast.tsx
src/constants/AuthModal.ts
src/index.tsx
src/mocks/data/AuthModal.ts
src/pages/FCFSEventPage/FCFSEventPage.stories.tsx
src/pages/FCFSEventPage/FCFSEventPage.tsx
src/pages/FCFSEventResultPage/FCFSEventResultPage.stories.tsx
src/pages/FCFSEventResultPage/FCFSEventResultPage.test.tsx
src/pages/authModal/AuthModal.test.tsx
src/pages/authModal/AuthModal.tsx
src/pages/mainPage/MainPage.tsx
src/router/router.tsx
src/styles/keyframes.ts
src/styles/options.ts
src/styles/tailwind.ts
src/types/tailwind.ts
src/utils/auth.ts
webpack.common.js
webpack.dev.js
webpack.prod.js

#50 
- 타이머 설정이 여러 곳에서 있어서 useTimer Custom Hook을 만들었다. 
```javascript
const TimerComponent = () => {
const { reset, minutes, second } = useTimer(1000, () => navigate("/"));
return (
<div>
{minutes} : {second}
</div>
);
};
```
초기 설정 시간과 종료 시 실행될 로직을 매개변수로 전달하면 된다.
- url을 변경하면서 modal을 띄우는 동시에 이전 화면을 뒷 배경으로 보여주려고 하였다. 다음과 같은 블로그를 참고했다.
[리액트 라우터 v6를 이용해 쉽게 모달 만들기](https://itchallenger.tistory.com/603)
- useLocation
[[React - 17] useLocation](https://white120.tistory.com/94)
---
- 모달 띄우기
[Create contextual modal navigation with React Router V6.](https://dev.to/devmdmamun/create-contextual-modal-navigation-with-react-router-v6-28k2)
이 상황은 사용자가 웹사이트를 처음 방문하거나, 특정 URL(예: `/modal`)로 직접 접근했을 때 발생합니다. 이 경우 `background`는 `null` 또는 `undefined`이고, `location`이 현재 위치를 나타내므로, `location={background || …

[Feature] Auth modal 구현

---

src/pages/mainPage/InfoScreen/ColorSection.tsx
src/pages/mainPage/InfoScreen/PerformanceSection.tsx

#63 
sticky와 clippath를 사용하여 스크롤에 따라 색상이 자연스럽게 바뀌는 자동차 이미지를 구현했다. 
```javascript
const render = () => {
if (divRef.current) {
const imageHeight = divRef.current.offsetHeight / colorInfo.length;
const scrollPosition = -divRef.current.getBoundingClientRect().y;
const newClipPosition = colorInfo.map((_, index) => {
const imageOffset = (index + 1) * imageHeight;
if (
imageOffset < scrollPosition &&
scrollPosition < imageOffset + imageHeight
) {
return ((scrollPosition - imageOffset) / imageHeight) * 100;
} else if (imageOffset < scrollPosition) {
return 100;
} else {
return 0;
}
});
setClipPosition(newClipPosition);
}
requestAnimationFrame(render);
};
```
다음과 같은 로직을 통해 이미지가 clip되는 정도를 스크롤에 따라 변경하였다. 여기서 `imageOffset = index * imageHeight;`이 아닌 `imageOffset = (index + 1) * imageHeight;`를 사용하여 …

[Feature] 자동차 스크롤 시 색상이 변경되는 컴포넌트 구현

---

src/components/common/AuthTooltip/AuthTooltip.stories.tsx
src/components/common/Button/Button.stories.tsx
src/components/common/Carousel/Carousel.stories.tsx
src/components/common/Glow/Glow.stories.tsx
src/components/common/HomeButton/HomeButton.stories.tsx
src/components/common/Toast/Toast.stories.tsx
src/components/mainPage/MainScreen/EventHeader.stories.tsx
src/components/mainPage/MainScreen/EventSelectOptions/EventSelectOptions.stories.tsx
src/components/randomEventPage/Option/Option.stories.tsx
src/components/randomEventPage/ProgressBar/ProgressBar.stories.tsx
src/components/randomEventPage/Roulette/Roulette.stories.tsx
src/components/randomEventPage/Tooltip/Tooltip.stories.tsx
src/constants/EventData.ts
src/constants/RandomEventData.ts
src/pages/FCFSEventPage/FCFSEventPage.stories.tsx
src/pages/FCFSEventPage/FCFSHintSection.stories.tsx
src/pages/FCFSEventPage/FCFSQuizSection.stories.tsx
src/pages/FCFSEventResultPage/FCFSEventResultPage.stories.tsx
src/pages/authModal/AuthModal.stories.tsx
src/pages/mainPage/InfoScreen/PerformanceSection.stories.tsx
src/pages/mainPage/MainScreen/EventSelectSection.tsx
src/pages/mainPage/MainScreen/FCFSEventSection.stories.tsx
src/pages/mainPage/MainScreen/RandomEventSection.stories.tsx
src/pages/randomEventPage/RandomQuizSection.stories.tsx
src/pages/randomEventResultPage/RandomExpectations/RandomExpectations.stories.tsx
src/pages/randomEventResultPage/RandomMainSection/RandomMainSection.stories.tsx

[Refactor] main page

---

src/client/api/fetch.ts
src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
src/client/types/InfoScreen.ts

[!HotFix] api 경로 수정

---

src/admin/components/FCFSWinnersPopup/FCFSWinnersPopup.tsx
src/admin/components/RandomWinnersPopup/RandomWinnersPopup.tsx
src/admin/pages/CreateEvent/CreateEvent.tsx
src/admin/pages/EventManagement/EventManagement.tsx
src/admin/pages/FCFSParticipants/FCFSParticipants.tsx
src/admin/pages/RandomParticipants/RandomParticipants.tsx
src/admin/router/router.tsx

[Feature] admin layout

---

src/admin/api/fetch.ts
src/admin/constants/constants.tsx
src/admin/pages/FCFSParticipants/FCFSParticipants.tsx
src/admin/pages/RandomParticipants/RandomParticipants.tsx
src/admin/router/router.tsx
src/admin/types/event.ts

- #82 
`const response = await fetch(`/admin/arrival/applicationList?page=${page}`);`
- 이런식으로 get 요청을 보내면 page에 맞는 정보를 가져올 수 있음

[Feature] admin 참여자 목록 api 연결

---

src/client/components/mainPage/MainScreen/Timer/Timer.stories.tsx
src/client/components/mainPage/MainScreen/Timer/Timer.test.tsx
src/client/components/mainPage/MainScreen/Timer/Timer.tsx
src/client/hooks/useTimer.tsx
src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
src/client/pages/mainPage/MainScreen/RandomEventSection/RandomEventSection.test.tsx
src/client/pages/mainPage/MainScreen/RandomEventSection/RandomEventSection.tsx

- #53 
- 서버 시간과 클라이언트 시간 동기화 방법
- 일반적인 서버 시간 호출로는 RTT를 고려하지 못함
- RTT 보정 방식
- 주기적으로 서버 시간 호출
- 정확도가 조금 떨어짐
- SEE
- 서버 사이드 이벤트
- 서버에서 클라이언트로의 단방향 통신
- HTTP 프로토콜을 이용
- 참고
- 프론트: [블로그](https://velog.io/@nagosu/Last-Pang-SSE-%EC%8B%9C%EA%B0%84-%EB%8F%99%EA%B8%B0%ED%99%94-%EB%B0%8F-%EC%B9%B4%EC%9A%B4%ED%8A%B8%EB%8B%A4%EC%9A%B4-%EA%B5%AC%ED%98%84)
- 백: [블로그](https://velog.io/@black_han26/SSE-Server-Sent-Events)

[Feature] 타이머 구현

---

public/share.css
public/share.html
src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.stories.tsx

[Feature] 공유 받는 페이지 구현

---

src/client/components/common/Toast/Toast.tsx
src/client/components/mainPage/MainScreen/Timer/Timer.tsx
src/client/constants/RandomEventData.ts
src/client/hooks/useTimer.tsx
src/client/pages/randomEventPage/RandomEventPage.tsx
src/client/pages/randomEventResultPage/RandomEventResultPage.tsx
src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx
src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx

[Feature] multiple issues

---

src/admin/api/fetch.ts
src/admin/pages/EventManagement/EventManagement.tsx
src/admin/pages/LogManagement/LogManagement.tsx
src/admin/router/router.tsx
src/admin/types/event.ts
src/client/App.tsx
src/client/components/common/AuthTooltip/AuthTooltip.tsx
src/client/components/mainPage/MainScreen/Timer/Timer.test.tsx
src/client/components/mainPage/MainScreen/Timer/Timer.tsx
src/client/mocks/data/AuthModal.ts
src/client/pages/FCFSEventPage/FCFSEventPage.tsx
src/client/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
src/client/pages/fallbackPage/FallbackPage.tsx
src/client/pages/mainPage/MainPage.tsx
src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.test.tsx
src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
src/client/pages/randomEventResultPage/RandomEventResultPage.tsx
src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
src/client/router/router.tsx

[Refactor] 에러 바운더리 시, await 추가 및 어드민 로그 페이지 생성

---

src/admin/api/fetch.ts
src/admin/components/FCFSWinnersPopup/FCFSWinnersPopup.tsx
src/admin/components/RandomWinnersPopup/RandomWinnersPopup.tsx
src/admin/pages/FCFSParticipants/FCFSParticipants.tsx
src/admin/pages/RandomParticipants/RandomParticipants.tsx
src/admin/types/event.ts

- #82 
https://github.com/user-attachments/assets/d9666d8a-e380-41a4-b5ca-ab44a4983ecd

[Feature] admin 참여자 페이지 검색 구현

---

src/admin/api/fetch.ts
src/admin/pages/CreateEvent/CreateEvent.tsx
src/admin/types/event.ts
src/client/components/common/AuthTooltip/AuthTooltip.tsx
src/client/components/mainPage/MainScreen/Timer/Timer.tsx
src/client/mocks/data/AuthModal.ts
src/client/pages/FCFSEventPage/FCFSEventPage.tsx
src/client/pages/mainPage/MainPage.tsx
src/client/pages/randomEventResultPage/RandomEventResultPage.tsx
src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx

[Feature] 어드민 og 이미지 변경 기능 구현 및 타이머 표시 문구 변경

---

.gitignore
package.json
webpack.common.js
webpack.config.js
webpack.dev.js
webpack.prod.js
yarn.lock

[Chore] 환경변수 설정

---

src/client/index.tsx
webpack.common.js

[Hotfix] webpack 빌드 분기 설정

---

src/client/components/common/AuthTooltip/AuthTooltip.tsx
src/client/mocks/data/AuthModal.ts
src/client/mocks/handler/AuthModal.ts
src/client/mocks/handler/FCFSEvent.ts
src/client/pages/FCFSEventPage/FCFSEventPage.tsx
src/client/pages/FCFSEventResultPage/FCFSEventResultPage.tsx
src/client/pages/authModal/AuthModal.test.tsx
src/client/pages/authModal/AuthModal.tsx
src/client/pages/mainPage/MainPage.tsx
src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
src/client/pages/randomEventResultPage/RandomEventResultPage.tsx
src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
webpack.common.js

[!HOTFIX] cors 분기 처리

---

public/share.css
public/share.html
src/client/api/fetch.ts
src/client/components/mainPage/InfoScreen/DriveDescriptionItem/DriveDescriptionItem.tsx
src/client/pages/mainPage/InfoScreen/DriveSection/DriveSection.tsx
src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx

[Refactor] 최적화 및 오류 수정

---

package.json
src/admin/api/fetch.ts
src/client/components/mainPage/InfoScreen/DriveDescriptionItem/DriveDescriptionItem.test.tsx
src/client/pages/FCFSEventPage/FCFSEventPage.tsx
src/client/pages/mainPage/MainScreen/FCFSEventSection/FCFSEventSection.tsx
src/client/pages/mainPage/MainScreen/MainScreen.tsx
src/client/router/router.tsx
webpack.common.js
webpack.config.js
webpackUtil.js

[Feat] 어드민 배포 및 404 페이지 추가

---

public/share.html
src/client/components/mainPage/InfoScreen/WordCloud.tsx
src/client/constants/common.ts
src/client/pages/mainPage/NotificationScreen/NotificationScreen.tsx
src/client/pages/randomEventResultPage/RandomExpectations/RandomExpectations.tsx
src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.tsx
src/client/types/RandomEvent.ts

[Feature] event2 결과창 이슈

---

src/client/components/common/Glow/Glow.tsx
src/client/pages/FCFSEventPage/FCFSQuizSection/FCFSQuizSection.tsx
src/client/pages/randomEventResultPage/RandomMainSection/RandomMainSection.test.tsx

[Feature] ux 개선, 테스트코드 수정
